version: '2'
services:
  postgres:
    image: postgres
    volumes:
        - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lux_dev

  os-viewer:
    build:
      context: ./osviewer
    environment:
      - "OS_VIEWER_BASE_PATH="
    volumes:
      - ./os_viewer_themes:/app/app/config/themes
    ports:
      - "5000:5000"

  microsite:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
      - OS_VIEWER_HOST=http://localhost:5000

volumes:
  data: